name: 'Radix Actions'
description: 'Wrapper for Radix CLI commands'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN from the workflow which is executing this Action. Necessary to avoid GitHub API rate limits.'
  args2:
    description: 'Radix CLI arguments'
outputs:
  result:
    description: 'Result of command'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args2 }}
    - --token-environment
  env:
    github_token: ${{ inputs.github-token }}
