name: 'Radix Github Action'
description: 'Installs Radix CLI (rx) in your runner and optionally login and cleanup afterwards.'
inputs:
  version:
    description: 'Default is latest. Select the version of the Radix CLI (rx) to install.'
    required: false
  azure_client_id:
    description: 'Unless authenticate is set to false, this is requried and must be the Application(client) ID of the Azure Managed Identity, or the Azure App Registration to authenticate with.'
    required: false
  azure_client_secret:
    description: ' If set use this instead of Github Workload Identity (Github Workload Identity must be configured as a federated credential on your App Registration or Managed Identity to work). '
    required: false
  skip_authenticate:
    description: 'No authentication will be performed.'
    required: false

runs:
  using: 'node20'
  main: 'lib/main/index.js'
  post: 'lib/cleanup/index.js'
