name: CD

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    name: Modifiy repository files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read RX-Version
        id: read
        run: |
          version=$(grep 'ARG RX_VERSION=' Dockerfile | awk -F '"' '{print $2}')
          echo "version=${version}" >> "$GITHUB_OUTPUT"

      # Copied from https://gist.github.com/bitmvr/9ed42e1cc2aac799b123de9fdc59b016
      - name: Parse SemVer
        id: semver
        run: |
          VERSION="${{steps.read.outputs.version}}"
          VERSION="${VERSION#[vV]}"
          VERSION_MAJOR="${VERSION%%\.*}"
          VERSION_MINOR="${VERSION#*.}"
          VERSION_MINOR="${VERSION_MINOR%.*}"
          VERSION_PATCH="${VERSION##*.}"

          echo "Version: ${VERSION}"
          echo "Version [major]: ${VERSION_MAJOR}"
          echo "Version [minor]: ${VERSION_MINOR}"
          echo "Version [patch]: ${VERSION_PATCH}"
          
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "major=${VERSION_MAJOR}" >> "$GITHUB_OUTPUT"
          echo "minor=${VERSION_MINOR}" >> "$GITHUB_OUTPUT"
          echo "patch=${VERSION_PATCH}" >> "$GITHUB_OUTPUT"

      - name: Validate semver
        run: |
          echo "Version: $SEMVER"
          if [[ $SEMVER =~ ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$ ]]; then echo "success" && exit 0; fi;
          
          echo "failed"
          exit 1
        env:
          SEMVER: ${{steps.semver.outputs.version}}

      - name: Tag new versions from Dockerfile
        run: |
          git config user.name "${{github.event.actor.login}} <from-workflow-dispatch>"
          git config user.email github-actions@github.com
          echo Publishing ${{inputs.major}}.${{inputs.minor}}.${{inputs.patch}}
          
          git tag v${{steps.semver.outputs.major}}
          git tag v${{steps.semver.outputs.major}}.${{steps.semver.outputs.minor}}.${{steps.semver.outputs.patch}}
          git push origin v${{steps.semver.outputs.major}} --force
          git push origin v${{steps.semver.outputs.major}}.${{steps.semver.outputs.minor}}.${{steps.semver.outputs.patch}}
